x = "Hello World"	str	
x = 20	int	
x1 = 20.5	
x2 = 1j
x3 = ["apple", "banana", "cherry"]	
x4 = ("apple", "banana", "cherry")	
x5 = range(6)
x6 = {"name" : "John", "age" : 36}	
x7 = {"apple", "banana", "cherry"}
x8 = frozenset({"apple", "banana", "cherry"})	
x9 = True	
x10 = b"Hello"	
x11 = bytearray(5)		
x12 = memoryview(bytes(5))
x13 = None